### ISSUE TITLE
External IP

### ISSUE THREAD

**Issue by drewbug** [wconrad/ftpd#35]
I'm using Ftpd and loving every minute of it. It was so easy to subclass Ftpd::ReadOnlyDiskFileSystem and customize who can see what.

However, I'm running into an issue. Our server is behind a NAT and people are complaining about the "Server sent passive reply with unroutable address." error message they're seeing because Ftpd sends out our local address. Most clients fallback to using the server address, but I'm wondering if there's any way to properly fix the issue.

Is there a good way I can make Ftpd send clients our public IP? I know that there are some routers that will take care of this with packet rewriting, but we're using TLS so that option is out. The best I've gotten so far is this hack:

```
class TCPServer
  prepend(Module.new do
    def addr
      caller_locations.first.label == 'cmd_pasv' ? super.fill('203.0.113.197', 3, 1) : super
    end
  end)
end
```

This, of course, isn't ideal.

**Comment by wconrad** [comment]
Thank you for the kind words, and the bug report.  The way the passive-mode code is written makes me think it would never work behind a NAT, so you must be the first to try: It's not a bug you've found as much as it's missing functionality.  Most ftp servers have configuration options that you can use to get them to advertise the IP of your choice for passive mode connections.  I think ftpd will need that, too.

For reference, here's the code that establishes the passive mode socket server and advertises the IP, from https://github.com/wconrad/ftpd/blob/6214d4800164304a18651a48d15a06447e317a2b/lib/ftpd/cmd_pasv.rb :

        interface = socket.addr[3]
        self.data_server = TCPServer.new(interface, 0)
        ip = data_server.addr[3]
        port = data_server.addr[1]
        quads = [
          ip.scan(/\d+/),
          port >> 8,
          port & 0xff,
        ].flatten.join(',')
        reply "227 Entering passive mode (#{quads})"

Yeah, that's never going to work behind a NAT firewall.  The fix I have in mind will introduce a configuration variable for the advertised IP.  The line `ip = data_server.addr[3]` will change to something like `ip = configured_public_ip || data_server.addr[3]`.

I'll see what I can cook up in the way of a fix.  I'm not sure when I'll get to it--hopefully this weekend.

**Comment by drewbug** [comment]
That would really be great. Thanks so much for the hard work you do on this project.

**Comment by wconrad** [comment]
If you are able to modify your Gemfile to point to a specific branch of ftpd, then could you please test the _nat_ branch using this Gemfile line?

    gem 'ftpd', git: "https://github.com/wconrad/ftpd", branch: "nat"

The new configuration item is called #nat_ip.  Set it before starting the server, like so:

    ftp_server = Ftpd::FtpServer.new(@driver)
    ftp_server.nat_ip = "203.0.113.197"
    ftp_server.start

If you can't test the branch easily, I'll just publish it as a new gem version and you can try it that way.  It's a low risk change that's unlikely to break anything else, so that'd be OK.

Some people running an ftp server behind a firewall need to configure the port range that is used for passive server sockets.  I haven't added that option yet.  Let me know if you need it.

**Comment by wconrad** [comment]
The `nat` branch now has the option `passive_ports` which you can use to configure the range of ports to be used for passive-mode sockets.

**Comment by wconrad** [comment]
I don't think these "nat" changes will break anything, and the tests show that they probably fix this issue, so I'll merge this branch in and publish a new gem version.  The new gem version is coming with a another change (frozen strings) that is unlikely to break anyone, but could, so first gem version with these "nat" changes will be 2.0.0.

**Comment by drewbug** [comment]
Thanks so much for adding these features! We're now using the `nat_ip` config option in production. Sincerely appreciated.

**Comment by wconrad** [comment]
@drewbug It made my day that you are using this feature in production.  Thanks!
