### ISSUE TITLE
Can I hooking filesystem operations 

### ISSUE THREAD

**Issue by simon435500** [wconrad/ftpd#38]
I want to create a ftp server only allow user upload files/directories.

After user upload finished, this server will automatically do some operations.

Can I do this thing use ftpd?

**Comment by wconrad** [comment]
@simon435500 

I've created an example of a write-only file system for FTPD: https://github.com/wconrad/ftpd/blob/master/examples/write_only.rb

You can put any code you like in the file system driver's [#write method](https://github.com/wconrad/ftpd/blob/f9c0def7e474561db53b9023104b02c49ab6ae35/examples/write_only.rb#L30)

**Comment by simon435500** [comment]
@wconrad, thanks for your help.
I will try to build FTPD by this sample .

**Comment by wconrad** [comment]
I'll close this issue, but if the above suggestions did not work for you, please feel free to open another issue.
