### ISSUE TITLE
add bindir in gemspec 

### ISSUE THREAD

**Issue by KINGSABRI** [wconrad/ftpd#43]
The binary file `bin/ftpdrb` has not been linked in system correct path for executables. Generally it's `/usr/local/bin/ftpdrb` the contents of the current file is 
```
#!/usr/bin/ruby2.4
#
# This file was generated by RubyGems.
#
# The application 'ftpd' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0.a"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end

load Gem.activate_bin_path('ftpd', 'ftpdrb', version)
```
I belive the gemspec file is missing 

```
s.bindir        = "bin"
```

**Comment by wconrad** [comment]
I'm not positive that the `bindir` switch is needed.  I suspect that "bin" is its default.  I've made some changes to `ftpdrb` since version 2.0.2, including one specifically to make `ftpdrb` execute properly.  Are you still having trouble with it?

**Comment by KINGSABRI** [comment]
It's working fine now.
Thanks!
